### ISSUE TITLE
ImportError: dlopen(…/kerberos.cpython-36m-darwin.so, 2): Symbol not found

### ISSUE THREAD

**Issue by jmehnle** [02strich/pykerberos#37]
I'm on macOS X 10.13.2 (High Sierra), Python 3.6.5 installed via MacPorts, and `pykerberos` 1.2.1 installed via pip:

```
$ pip-3.6 show pykerberos
Name: pykerberos
Version: 1.2.1
Summary: High-level interface to Kerberos
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: ASL 2.0
Location: /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires:
Required-by:
```

I'm unable to `import kerberos`, however:

```
$ python3.6
Python 3.6.5 (default, Mar 29 2018, 15:37:32)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import kerberos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kerberos.cpython-36m-darwin.so, 2): Symbol not found: _mempcpy
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kerberos.cpython-36m-darwin.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kerberos.cpython-36m-darwin.so
```

I don't even know how to debug this. Help!

**Comment by jmehnle** [comment]
A manual build via `python3.6 setup.py build` doesn't work either. Here's the build log:

```
joule:~/tmp/pykerberos @master u=> python3.6 setup.py build
running build
running build_ext
building 'kerberos' extension
creating build
creating build/temp.macosx-10.13-x86_64-3.6
creating build/temp.macosx-10.13-x86_64-3.6/src
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I/opt/local/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/kerberos.c -o build/temp.macosx-10.13-x86_64-3.6/src/kerberos.o -I/opt/local/include -DGSSAPI_EXT
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I/opt/local/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/kerberosbasic.c -o build/temp.macosx-10.13-x86_64-3.6/src/kerberosbasic.o -I/opt/local/include -DGSSAPI_EXT
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I/opt/local/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/kerberosgss.c -o build/temp.macosx-10.13-x86_64-3.6/src/kerberosgss.o -I/opt/local/include -DGSSAPI_EXT
src/kerberosgss.c:402:29: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
        if (len-4-token_len < 0)
            ~~~~~~~~~~~~~~~ ^ ~
src/kerberosgss.c:876:14: warning: implicit declaration of function 'mempcpy' is invalid in C99 [-Wimplicit-function-declaration]
    outloc = mempcpy(outloc, iov[1].buffer.value, iov[1].buffer.length);
             ^
src/kerberosgss.c:876:14: warning: this function declaration is not a prototype [-Wstrict-prototypes]
src/kerberosgss.c:876:12: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
    outloc = mempcpy(outloc, iov[1].buffer.value, iov[1].buffer.length);
           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 warnings generated.
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I/opt/local/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/kerberospw.c -o build/temp.macosx-10.13-x86_64-3.6/src/kerberospw.o -I/opt/local/include -DGSSAPI_EXT
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I/opt/local/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/base64.c -o build/temp.macosx-10.13-x86_64-3.6/src/base64.o -I/opt/local/include -DGSSAPI_EXT
creating build/lib.macosx-10.13-x86_64-3.6
/usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names build/temp.macosx-10.13-x86_64-3.6/src/kerberos.o build/temp.macosx-10.13-x86_64-3.6/src/kerberosbasic.o build/temp.macosx-10.13-x86_64-3.6/src/kerberosgss.o build/temp.macosx-10.13-x86_64-3.6/src/kerberospw.o build/temp.macosx-10.13-x86_64-3.6/src/base64.o -o build/lib.macosx-10.13-x86_64-3.6/kerberos.cpython-36m-darwin.so -L/opt/local/lib -dynamic -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err
```

**Comment by jmehnle** [comment]
I tried building with GCC (via MacPorts), but I keep getting the same problem.

**Comment by jmehnle** [comment]
`pykerberos` 1.1.14 loads fine. I'm falling back to that in my project for now.

**Comment by 02strich** [comment]
@jmehnle the manual build output only contains warnings, but no errors. Did you get an error message as well (that got truncated here)?

**Comment by jmehnle** [comment]
When building `pykerberos` the above is all I get. No errors.

I get this file out of the build:

```
-rwxr-xr-x  1 julian  staff  42912 Jun 14 15:27 build/lib.macosx-10.13-x86_64-3.6/kerberos.cpython-36m-darwin.so*
```

**Comment by 02strich** [comment]
Then looks like the build is successful. When you install this and import it, what happens? Please make sure to Uninstall prior versions as well.

Sent from my iPhone

On Jun 14, 2018, at 08:28, Julian Mehnle <notifications@github.com<mailto:notifications@github.com>> wrote:


When building pykerberos the above is all I get. No errors.

I get this file out of the build:

-rwxr-xr-x  1 julian  staff  42912 Jun 14 15:27 build/lib.macosx-10.13-x86_64-3.6/kerberos.cpython-36m-darwin.so*

**Comment by jmehnle** [comment]
Sorry for sleeping on this so long. Work was too hectic, and I actually don't have much to clarify. When I build manually, install, and `import`, I get the same error message as originally reported:

```
joule:~/tmp/pykerberos @master u=> virtualenv-3.6 ~/pyvenv/pykerberos-py3.6
Using base prefix '/opt/local/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/julian/pyvenv/pykerberos-py3.6/bin/python3.6
Also creating executable in /Users/julian/pyvenv/pykerberos-py3.6/bin/python
Installing setuptools, pip, wheel...done.

joule:~/tmp/pykerberos @master u=> . ~/pyvenv/pykerberos-py3.6/bin/activate

(pykerberos-py3.6) joule:~/tmp/pykerberos @master u=> python setup.py build
running build
running build_ext
building 'kerberos' extension
creating build
creating build/temp.macosx-10.13-x86_64-3.6
creating build/temp.macosx-10.13-x86_64-3.6/src
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I/opt/local/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/kerberos.c -o build/temp.macosx-10.13-x86_64-3.6/src/kerberos.o -I/opt/local/include -DGSSAPI_EXT
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I/opt/local/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/kerberosbasic.c -o build/temp.macosx-10.13-x86_64-3.6/src/kerberosbasic.o -I/opt/local/include -DGSSAPI_EXT
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I/opt/local/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/kerberosgss.c -o build/temp.macosx-10.13-x86_64-3.6/src/kerberosgss.o -I/opt/local/include -DGSSAPI_EXT
src/kerberosgss.c:402:29: warning: comparison of unsigned expression < 0 is always false
      [-Wtautological-compare]
        if (len-4-token_len < 0)
            ~~~~~~~~~~~~~~~ ^ ~
src/kerberosgss.c:876:14: warning: implicit declaration of function 'mempcpy' is invalid in C99
      [-Wimplicit-function-declaration]
    outloc = mempcpy(outloc, iov[1].buffer.value, iov[1].buffer.length);
             ^
src/kerberosgss.c:876:14: warning: this function declaration is not a prototype
      [-Wstrict-prototypes]
src/kerberosgss.c:876:12: warning: incompatible integer to pointer conversion assigning to 'char *'
      from 'int' [-Wint-conversion]
    outloc = mempcpy(outloc, iov[1].buffer.value, iov[1].buffer.length);
           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 warnings generated.
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I/opt/local/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/kerberospw.c -o build/temp.macosx-10.13-x86_64-3.6/src/kerberospw.o -I/opt/local/include -DGSSAPI_EXT
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I/opt/local/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/base64.c -o build/temp.macosx-10.13-x86_64-3.6/src/base64.o -I/opt/local/include -DGSSAPI_EXT
creating build/lib.macosx-10.13-x86_64-3.6
/usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names build/temp.macosx-10.13-x86_64-3.6/src/kerberos.o build/temp.macosx-10.13-x86_64-3.6/src/kerberosbasic.o build/temp.macosx-10.13-x86_64-3.6/src/kerberosgss.o build/temp.macosx-10.13-x86_64-3.6/src/kerberospw.o build/temp.macosx-10.13-x86_64-3.6/src/base64.o -o build/lib.macosx-10.13-x86_64-3.6/kerberos.cpython-36m-darwin.so -L/opt/local/lib -dynamic -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err

(pykerberos-py3.6) joule:~/tmp/pykerberos @master u=> python setup.py install
running install
running bdist_egg
running egg_info
creating pykerberos.egg-info
writing pykerberos.egg-info/PKG-INFO
writing dependency_links to pykerberos.egg-info/dependency_links.txt
writing top-level names to pykerberos.egg-info/top_level.txt
writing manifest file 'pykerberos.egg-info/SOURCES.txt'
reading manifest file 'pykerberos.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pykerberos.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.13-x86_64/egg
running install_lib
running build_ext
creating build/bdist.macosx-10.13-x86_64
creating build/bdist.macosx-10.13-x86_64/egg
copying build/lib.macosx-10.13-x86_64-3.6/kerberos.cpython-36m-darwin.so -> build/bdist.macosx-10.13-x86_64/egg
creating stub loader for kerberos.cpython-36m-darwin.so
byte-compiling build/bdist.macosx-10.13-x86_64/egg/kerberos.py to kerberos.cpython-36.pyc
creating build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying pykerberos.egg-info/PKG-INFO -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying pykerberos.egg-info/SOURCES.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying pykerberos.egg-info/dependency_links.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying pykerberos.egg-info/top_level.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.13-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.kerberos.cpython-36: module references __file__
creating dist
creating 'dist/pykerberos-1.2.2.dev0-py3.6-macosx-10.13-x86_64.egg' and adding 'build/bdist.macosx-10.13-x86_64/egg' to it
removing 'build/bdist.macosx-10.13-x86_64/egg' (and everything under it)
Processing pykerberos-1.2.2.dev0-py3.6-macosx-10.13-x86_64.egg
creating /Users/julian/pyvenv/pykerberos-py3.6/lib/python3.6/site-packages/pykerberos-1.2.2.dev0-py3.6-macosx-10.13-x86_64.egg
Extracting pykerberos-1.2.2.dev0-py3.6-macosx-10.13-x86_64.egg to /Users/julian/pyvenv/pykerberos-py3.6/lib/python3.6/site-packages
Adding pykerberos 1.2.2.dev0 to easy-install.pth file

Installed /Users/julian/pyvenv/pykerberos-py3.6/lib/python3.6/site-packages/pykerberos-1.2.2.dev0-py3.6-macosx-10.13-x86_64.egg
Processing dependencies for pykerberos==1.2.2.dev0
Finished processing dependencies for pykerberos==1.2.2.dev0

(pykerberos-py3.6) joule:~/tmp/pykerberos @master u=> python
Python 3.6.5 (default, Mar 29 2018, 15:37:32)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import kerberos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/julian/pyvenv/pykerberos-py3.6/lib/python3.6/site-packages/pykerberos-1.2.2.dev0-py3.6-macosx-10.13-x86_64.egg/kerberos.cpython-36m-darwin.so, 2): Symbol not found: _mempcpy
  Referenced from: /Users/julian/pyvenv/pykerberos-py3.6/lib/python3.6/site-packages/pykerberos-1.2.2.dev0-py3.6-macosx-10.13-x86_64.egg/kerberos.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/julian/pyvenv/pykerberos-py3.6/lib/python3.6/site-packages/pykerberos-1.2.2.dev0-py3.6-macosx-10.13-x86_64.egg/kerberos.cpython-36m-darwin.so
```

**Comment by jmehnle** [comment]
No, this is not the first C extension I'm installing with Python 3.6 here. I didn't compile Python myself but installed it from [MacPorts](https://www.macports.org). I then created a virtualenv and installed & compiled `pykerberos` inside of that, as far as I can tell using the MacPorts-provided build chain (gcc, etc.).

```
(pykerberos-py3.6) joule:~> otool -L /Users/julian/pyvenv/pykerberos-py3.6/lib/python3.6/site-packages/pykerberos-1.2.2.dev0-py3.6-macosx-10.13-x86_64.egg/kerberos.cpython-36m-darwin.so
/Users/julian/pyvenv/pykerberos-py3.6/lib/python3.6/site-packages/pykerberos-1.2.2.dev0-py3.6-macosx-10.13-x86_64.egg/kerberos.cpython-36m-darwin.so:
	/opt/local/lib/libgssapi_krb5.2.2.dylib (compatibility version 2.0.0, current version 2.2.0)
	/opt/local/lib/libkrb5.3.3.dylib (compatibility version 3.0.0, current version 3.3.0)
	/opt/local/lib/libk5crypto.3.1.dylib (compatibility version 3.0.0, current version 3.1.0)
	/opt/local/lib/libcom_err.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

**Comment by 02strich** [comment]
Running through this again with a fresh python, I do not get this error on my machine. Using master, I get the following dependencies on my machine:
build/lib.macosx-10.13-x86_64-3.6/kerberos.cpython-36m-darwin.so:
        /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)

(my python comes from pyenv as well, but I am using Homebrew/XCode)

**Comment by tucked** [comment]
I can reproduce this on a `freebsd12`-based system with 1.2.1:
```
# /root/venv/bin/python -c 'import kerberos'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /root/venv/lib/python2.7/site-packages/kerberos.so: Undefined symbol "mempcpy"
```
Is `mempcpy` Linux-specific?
https://github.com/02strich/pykerberos/blob/fda6916343cb95b14760a9a59d822c88e25c8781/src/kerberosgss.c#L876

**Comment by ngie-eign** [comment]
> Then looks like the build is successful. When you install this and import it, what happens? Please make sure to Uninstall prior versions as well.
> […](#)

The build was successful, but fails at runtime because the runtime linker can’t resolve the symbol.

1.2.1 was where the new symbols were added with commit 39ec626539.

**Comment by 02strich** [comment]
Do you need a new release on PyPi with the fix?

**Comment by tucked** [comment]
That would be great! `requests-kerberos` depends on this, and we would like to use that.

**Comment by 02strich** [comment]
I have uploaded a new version: https://pypi.org/project/pykerberos/1.2.3.dev0/

**Comment by tucked** [comment]
WFM, thanks! 🎉
